import 'package:app/pairing/pair_payload.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('PairPayload.tryParse', () {
    const goodToken = 'AAAAAAAAAAAAAAAAAAAAAA'; // 16 bytes base64url
    const goodEpk = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'; // 32 bytes
    const sessionName = 'test+session';

    test('parses legacy QR with relay (r=) param', () {
      final raw = 'remotepi://pair?t=$goodToken&epk=$goodEpk&'
          'r=ws%3A%2F%2Flocalhost&n=$sessionName';
      final qr = PairPayload.tryParse(raw);
      expect(qr, isNotNull);
      expect(qr!.token, goodToken);
      expect(qr.epk, goodEpk);
      expect(qr.sessionName, 'test session');
      expect(qr.relayUrl, 'ws://localhost',
          reason: 'legacy r= is parsed for mismatch detection');
    });

    test('parses new QR WITHOUT r= param — relayUrl is null', () {
      final raw =
          'remotepi://pair?t=$goodToken&epk=$goodEpk&n=$sessionName';
      final qr = PairPayload.tryParse(raw);
      expect(qr, isNotNull);
      expect(qr!.token, goodToken);
      expect(qr.epk, goodEpk);
      expect(qr.sessionName, 'test session');
      expect(qr.relayUrl, isNull,
          reason: 'no r= present — app uses its configured relay');
    });

    test('rejects when t is missing or wrong length', () {
      final missingT =
          'remotepi://pair?epk=$goodEpk&n=$sessionName';
      expect(PairPayload.tryParse(missingT), isNull);

      final badT = 'remotepi://pair?t=AAAA&epk=$goodEpk&n=$sessionName';
      expect(PairPayload.tryParse(badT), isNull);
    });

    test('rejects when epk has wrong byte length', () {
      final raw =
          'remotepi://pair?t=$goodToken&epk=AAAAAAAAA&n=$sessionName';
      expect(PairPayload.tryParse(raw), isNull);
    });

    test('rejects non-remotepi scheme', () {
      const raw =
          'https://example.com/pair?t=x&epk=y&n=z';
      expect(PairPayload.tryParse(raw), isNull);
    });

    test('empty r= is treated as null (not the empty string)', () {
      final raw = 'remotepi://pair?t=$goodToken&epk=$goodEpk&'
          'r=&n=$sessionName';
      final qr = PairPayload.tryParse(raw);
      expect(qr, isNotNull);
      expect(qr!.relayUrl, isNull);
    });

    test(
      'parses QR with `rm` (room id) — plan 17 fix lets the app target '
      'the Pi\'s cwd-session at pair_request time',
      () {
        final raw = 'remotepi://pair?t=$goodToken&epk=$goodEpk&'
            'rm=abc123def456&n=$sessionName';
        final qr = PairPayload.tryParse(raw);
        expect(qr, isNotNull);
        expect(qr!.roomId, 'abc123def456');
      },
    );

    test('QR without `rm` (legacy) leaves roomId null', () {
      final raw = 'remotepi://pair?t=$goodToken&epk=$goodEpk&n=$sessionName';
      final qr = PairPayload.tryParse(raw);
      expect(qr, isNotNull);
      expect(qr!.roomId, isNull);
    });

    test('empty rm= is treated as null', () {
      final raw = 'remotepi://pair?t=$goodToken&epk=$goodEpk&'
          'rm=&n=$sessionName';
      final qr = PairPayload.tryParse(raw);
      expect(qr, isNotNull);
      expect(qr!.roomId, isNull);
    });

    // Plan/68 — the payload is a frozen contract; removing the QR scan changed
    // only how the user obtains the string. Pin the app-side parser against the
    // exact byte string the extension's `buildQRUri` emits (all-zero 32-byte
    // key → "AAAA…"), so a builder/parser divergence fails here.
    test('parses the frozen extension payload byte-for-byte', () {
      const frozen =
          'remotepi://pair?t=$goodToken&epk=$goodEpk&n=test+session';
      final qr = PairPayload.tryParse(frozen);
      expect(qr, isNotNull);
      expect(qr!.token, goodToken);
      expect(qr.epk, goodEpk);
      expect(qr.sessionName, 'test session');
      expect(qr.relayUrl, isNull);
      expect(qr.roomId, isNull);
    });

    // Plan/69 W1 — regression: the HISTORICAL payload emitted by an older Pi
    // (legacy `r=` relay + plan-17 `rm=` room id) must keep parsing. Pairing
    // moved from Pi-issued to host-issued codes, but a code generated by an
    // old Pi still pairs through the Pi path — the URI is a frozen contract
    // and the parser is the app-side guardian of it.
    test('parses the historical Pi-issued payload (r= + rm=)', () {
      const historical = 'remotepi://pair?t=$goodToken&epk=$goodEpk&'
          'r=ws%3A%2F%2Flocalhost&rm=abc123def456&n=test+session';
      final qr = PairPayload.tryParse(historical);
      expect(qr, isNotNull);
      expect(qr!.token, goodToken);
      expect(qr.epk, goodEpk);
      expect(qr.sessionName, 'test session');
      expect(qr.relayUrl, 'ws://localhost');
      expect(qr.roomId, 'abc123def456');
    });
  });
}
