name: Build iOS IPA
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 指定在 app 子目录下运行（如果子目录名为 mobile，请改为 mobile）
      - name: Flutter Pub Get
        working-directory: app
        run: flutter pub get

      - name: Build IPA
        working-directory: app
        run: flutter build ipa --no-codesign

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: app/build/ios/archive/Runner.xcarchive/Products/Applications/
